pipeline {
    agent any
    environment {
        CI = true
    }
    stages {
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test application') {
            steps {
                sh '../jenkins/scripts/tests.sh'
            }
        }
        stage('Build application') {
            steps {
                sh 'npm build'
            }
        } 
        stage('Deploy') {
            steps {
                sh 'serve -s build'
            }
        }
    }
}